from __future__ import annotations

import csv
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from receipt_ocr.config import EVALUATION_DIR
from receipt_ocr.schema import ReceiptItem
from receipt_ocr.text_normalizer import (
    clean_line,
    find_money_values,
    is_probable_barcode,
    normalize_for_matching,
    parse_quantity,
)


LAYOUT_DEBUG_DIR = EVALUATION_DIR / "layout_debug"


ITEM_SECTION_START_KEYWORDS = [
    "MAT HANG",
    "TEN HANG",
    "TEN MON",
    "SAN PHAM",
    "ITEM",
    "DESCRIPTION",
    "DON GIA",
    "D GIA",
    "D.GIA",
    "DG",
    "SL",
]

ITEM_SECTION_END_KEYWORDS = [
    "TONG",
    "CONG TIEN",
    "THANH TOAN",
    "TIEN KHACH",
    "TIEN MAT",
    "TRA LAI",
    "VAT",
    "GTGT",
    "CAM ON",
    "THANK",
]


@dataclass
class LayoutRow:
    receipt_id: str
    row_id: int
    texts: list[str]
    x_mins: list[float]

    @property
    def text(self) -> str:
        return " | ".join(self.texts)


@dataclass
class LayoutParsedItem:
    receipt_id: str
    name: str
    quantity: float | None
    unit_price: int | None
    line_total: int | None
    source_row_id: int
    value_row_id: int | None
    strategy: str

    def to_receipt_item(self) -> ReceiptItem:
        return ReceiptItem(
            name=self.name,
            quantity=self.quantity,
            unit_price=self.unit_price,
            line_total=self.line_total,
        )


def normalize_layout_matching_text(value: Any) -> str:
    """
    Normalize OCR text for layout-row matching.

    This is used only for parser decisions such as:
    - item section start/end detection
    - metadata/summary/noise filtering

    It does not modify the original extracted text.
    """
    text = normalize_for_matching(str(value or ""))

    replacements = {
        "T8NG": "TONG",
        "T0NG": "TONG",
        "C0NG": "CONG",
        "T0AN": "TOAN",
        "THNH": "THANH",
        "THNH TIER": "THANH TIEN",
        "T TIER": "T TIEN",
        "LGI": "LAI",
        "MAL": "MAT",
    }

    for wrong, correct in replacements.items():
        text = text.replace(wrong, correct)

    text = re.sub(r"[^A-Z0-9]+", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    return text


def read_layout_rows(layout_csv_path: str | Path) -> list[LayoutRow]:
    """
    Read layout rows generated by scripts/inspect_ocr_layout.py.

    Expected CSV columns:
        row_id, text, x_min, ...
    """
    path = Path(layout_csv_path)

    if not path.exists():
        raise FileNotFoundError(f"Layout CSV not found: {path}")

    receipt_id = path.stem.replace("_layout_lines", "")

    with path.open("r", encoding="utf-8-sig", newline="") as file:
        records = list(csv.DictReader(file))

    grouped: dict[int, list[dict[str, str]]] = {}

    for record in records:
        row_id_text = record.get("row_id") or ""

        if not row_id_text:
            continue

        try:
            row_id = int(float(row_id_text))
        except ValueError:
            continue

        grouped.setdefault(row_id, []).append(record)

    rows: list[LayoutRow] = []

    for row_id, row_records in sorted(grouped.items()):
        row_records = sorted(
            row_records,
            key=lambda record: float(record.get("x_min") or 0),
        )

        texts = [clean_line(record.get("text", "")) for record in row_records]
        texts = [text for text in texts if text]

        x_mins = [float(record.get("x_min") or 0) for record in row_records]

        if texts:
            rows.append(
                LayoutRow(
                    receipt_id=receipt_id,
                    row_id=row_id,
                    texts=texts,
                    x_mins=x_mins,
                )
            )

    return rows


def row_normalized(row: LayoutRow) -> str:
    return normalize_layout_matching_text(row.text)


def is_header_row(row: LayoutRow) -> bool:
    normalized = row_normalized(row)
    return any(keyword in normalized for keyword in ITEM_SECTION_START_KEYWORDS)


def is_end_row(row: LayoutRow) -> bool:
    normalized = row_normalized(row)
    return any(keyword in normalized for keyword in ITEM_SECTION_END_KEYWORDS)


def find_item_section_rows(rows: list[LayoutRow]) -> list[LayoutRow]:
    """
    Locate item table rows between item header and total/payment section.
    """
    start_index = 0

    for index, row in enumerate(rows):
        if is_header_row(row):
            start_index = index + 1
            break

    end_index = len(rows)

    for index in range(start_index, len(rows)):
        if is_end_row(rows[index]):
            end_index = index
            break

    return rows[start_index:end_index]


def has_alpha(text: str) -> bool:
    return bool(re.search(r"[A-Za-zÀ-ỹ]", text))


def is_noise_name(text: str) -> bool:
    normalized_clean = normalize_layout_matching_text(text)

    if not normalized_clean:
        return True

    if len(normalized_clean) <= 2:
        return True

    noise_keywords = [
        "HOA DON",
        "PHIEU",
        "QUAY",
        "NVBH",
        "THU NGAN",
        "NHAN VIEN",
        "KHACH HANG",
        "KHACH LE",
        "HOTLINE",
        "TEL",
        "FAX",
        "WIFI",
        "CAM ON",
        "THANK",
        "TONG",
        "THANH TOAN",
        "TIEN",
        "TRA LAI",
        "GIAM",
        "CHIET KHAU",
        "VAT",
        "GTGT",
        "KM",
    ]

    if any(keyword in normalized_clean for keyword in noise_keywords):
        return True

    exact_headers = {
        "TT",
        "STT",
        "SL",
        "DG",
        "D GIA",
        "DON GIA",
        "GIA",
        "KM",
        "T TIEN",
        "THANH TIEN",
        "TEN MON",
        "TEN HANG",
        "MAT HANG",
    }

    if normalized_clean in exact_headers:
        return True

    standalone_noise_tokens = {
        "JENB",
        "DIA",
    }

    if normalized_clean in standalone_noise_tokens:
        return True

    return False


def is_probable_item_name_text(text: str) -> bool:
    text = clean_line(text)

    if not text:
        return False

    if not has_alpha(text):
        return False

    if is_probable_barcode(text):
        return False

    if find_money_values(text):
        return False

    if is_noise_name(text):
        return False

    return True


def extract_name_from_row(row: LayoutRow) -> str | None:
    """
    Extract item name from a layout row.

    Handles:
    - normal item name rows
    - multi-cell names such as "Sua chua | matcha"
    - compact temporary-bill text such as "1COCONUT"
    - temporary-bill text such as "1 APPLE TEAICE"
    """
    candidates: list[str] = []

    for text in row.texts:
        cleaned = clean_line(text)

        if is_probable_item_name_text(cleaned):
            candidates.append(cleaned)

    if not candidates:
        return None

    if len(candidates) >= 2:
        return clean_line(" ".join(candidates))

    name = candidates[0]

    match = re.match(r"^\d+(?:[,.]\d+)?\s+([A-Za-zÀ-ỹ].+)$", name)

    if match:
        return clean_line(match.group(1))

    match = re.match(r"^\d+([A-Za-zÀ-ỹ].+)$", name)

    if match:
        return clean_line(match.group(1))

    return name


def normalize_item_name_order(name: str) -> str:
    """
    Fix item-name fragments that OCR/layout order places in the wrong order.

    Example:
        Quat(Cay) Banh Mi Ga Kim
        -> Banh Mi Ga Kim Quat(Cay)
    """
    text = clean_line(name)

    if not text:
        return text

    normalized = normalize_layout_matching_text(text)

    if "BANH MI" in normalized and ("QUAT" in normalized or "CAY" in normalized):
        parts = text.split()

        modifier_parts = []
        main_parts = []

        for part in parts:
            part_normalized = normalize_layout_matching_text(part)

            if "QUAT" in part_normalized or "CAY" in part_normalized:
                modifier_parts.append(part)
            else:
                main_parts.append(part)

        if main_parts and modifier_parts:
            return clean_line(" ".join(main_parts + modifier_parts))

    return text


def collect_money_values(row: LayoutRow) -> list[int]:
    values: list[int] = []

    for text in row.texts:
        values.extend(find_money_values(text))

    return values


def collect_quantity_values(row: LayoutRow) -> list[float]:
    """
    Collect quantity values from a layout row.

    Handles cases such as:
        1Goi | 9,000 | 0 | 9,000
        2 | Sua chua | matcha | 1 | 25.000 | 25.000

    Rules:
    - Ignore money values and barcodes.
    - Ignore zero values, because they are often KM/discount columns.
    - If the first cell is a numeric-only STT/index and the row also contains
      item-name text, skip that first numeric cell.
    - Support compact quantity-unit OCR text such as `1Goi`.
    """
    quantities: list[float] = []

    has_name_text = any(
        has_alpha(text)
        and not find_money_values(text)
        and not is_probable_barcode(text)
        for text in row.texts
    )

    for cell_index, text in enumerate(row.texts):
        cleaned = clean_line(text)

        if not cleaned:
            continue

        if is_probable_barcode(cleaned):
            continue

        if find_money_values(cleaned):
            continue

        if (
            cell_index == 0
            and has_name_text
            and re.fullmatch(r"\d+", cleaned)
            and len(row.texts) >= 5
        ):
            continue

        compact_quantity_match = re.match(
            r"^(?P<quantity>\d+(?:[,.]\d+)?)\s*[A-Za-zÀ-ỹ]+$",
            cleaned,
        )

        if compact_quantity_match:
            quantity = parse_quantity(compact_quantity_match.group("quantity"))

            if quantity is not None and quantity > 0:
                quantities.append(quantity)

            continue

        quantity = parse_quantity(cleaned)

        if quantity is not None and quantity > 0:
            quantities.append(quantity)

    return quantities


def parse_values_from_row(row: LayoutRow) -> tuple[float | None, int | None, int | None]:
    money_values = collect_money_values(row)
    quantity_values = collect_quantity_values(row)

    quantity = quantity_values[0] if quantity_values else None
    unit_price = None
    line_total = None

    if len(money_values) >= 2:
        unit_price = money_values[0]
        line_total = money_values[-1]
    elif len(money_values) == 1:
        unit_price = money_values[0]
        line_total = money_values[0]

    return quantity, unit_price, line_total


def normalize_layout_item_values(item: LayoutParsedItem) -> LayoutParsedItem:
    """
    Fix common layout parser value issues.

    Examples:
    - If unit_price == line_total and quantity is missing, infer quantity = 1.
    - If quantity > 1 and only line_total was detected, infer unit_price = line_total / quantity.
    - If OCR produced tiny line_total such as 6 from `0006`, but unit_price is
      plausible, fall back line_total to unit_price.
    """
    quantity = item.quantity
    unit_price = item.unit_price
    line_total = item.line_total

    if unit_price is not None and line_total is not None:
        if line_total < 1000 and unit_price >= 1000:
            line_total = unit_price

        if (
            quantity is not None
            and quantity > 1
            and unit_price == line_total
            and line_total % quantity == 0
        ):
            inferred_unit_price = int(line_total / quantity)

            if inferred_unit_price >= 1000:
                unit_price = inferred_unit_price

        elif unit_price == line_total:
            quantity = 1

    return LayoutParsedItem(
        receipt_id=item.receipt_id,
        name=item.name,
        quantity=quantity,
        unit_price=unit_price,
        line_total=line_total,
        source_row_id=item.source_row_id,
        value_row_id=item.value_row_id,
        strategy=item.strategy,
    )


def parse_single_row_item(row: LayoutRow) -> LayoutParsedItem | None:
    name = extract_name_from_row(row)

    if not name:
        return None

    quantity, unit_price, line_total = parse_values_from_row(row)

    if unit_price is None and line_total is None:
        return None

    return normalize_layout_item_values(
        LayoutParsedItem(
            receipt_id=row.receipt_id,
            name=normalize_item_name_order(name),
            quantity=quantity,
            unit_price=unit_price,
            line_total=line_total,
            source_row_id=row.row_id,
            value_row_id=row.row_id,
            strategy="single_row",
        )
    )


def parse_name_value_pair(
    name_row: LayoutRow,
    value_row: LayoutRow,
) -> LayoutParsedItem | None:
    name = extract_name_from_row(name_row)

    if not name:
        return None

    quantity, unit_price, line_total = parse_values_from_row(value_row)

    if unit_price is None and line_total is None:
        return None

    return normalize_layout_item_values(
        LayoutParsedItem(
            receipt_id=name_row.receipt_id,
            name=normalize_item_name_order(name),
            quantity=quantity,
            unit_price=unit_price,
            line_total=line_total,
            source_row_id=name_row.row_id,
            value_row_id=value_row.row_id,
            strategy="name_value_pair",
        )
    )


def append_name_continuation_if_needed(
    item: LayoutParsedItem,
    section_rows: list[LayoutRow],
    next_index: int,
) -> tuple[LayoutParsedItem, int]:
    """
    Append short continuation rows to an already parsed item name.

    Example:
        Tran cha | 1 | 10.000 | 10.000
        duongder

    Expected name:
        Tran cha duongder

    Conservative rules:
    - only checks the immediate next row
    - only appends rows with text but no money values
    - does not append summary/end rows
    """
    if next_index >= len(section_rows):
        item.name = normalize_item_name_order(item.name)
        return item, next_index

    next_row = section_rows[next_index]

    if is_end_row(next_row):
        item.name = normalize_item_name_order(item.name)
        return item, next_index

    if collect_money_values(next_row):
        item.name = normalize_item_name_order(item.name)
        return item, next_index

    continuation_name = extract_name_from_row(next_row)

    if not continuation_name:
        item.name = normalize_item_name_order(item.name)
        return item, next_index

    if next_index + 1 < len(section_rows):
        row_after_next = section_rows[next_index + 1]

        if not is_end_row(row_after_next) and collect_money_values(row_after_next):
            item.name = normalize_item_name_order(item.name)
            return item, next_index

    merged_name = clean_line(f"{item.name} {continuation_name}")

    return (
        LayoutParsedItem(
            receipt_id=item.receipt_id,
            name=normalize_item_name_order(merged_name),
            quantity=item.quantity,
            unit_price=item.unit_price,
            line_total=item.line_total,
            source_row_id=item.source_row_id,
            value_row_id=item.value_row_id,
            strategy=f"{item.strategy}+name_continuation",
        ),
        next_index + 1,
    )


def parse_layout_items_from_rows(rows: list[LayoutRow]) -> list[LayoutParsedItem]:
    section_rows = find_item_section_rows(rows)

    items: list[LayoutParsedItem] = []
    index = 0

    while index < len(section_rows):
        row = section_rows[index]

        single_row_item = parse_single_row_item(row)

        if single_row_item is not None:
            single_row_item, next_index = append_name_continuation_if_needed(
                single_row_item,
                section_rows,
                index + 1,
            )

            items.append(single_row_item)
            index = next_index
            continue

        if is_probable_item_name_text(row.text):
            item_added = False

            for lookahead_index in range(index + 1, min(index + 4, len(section_rows))):
                value_row = section_rows[lookahead_index]

                if lookahead_index > index + 1 and is_probable_item_name_text(value_row.text):
                    break

                pair_item = parse_name_value_pair(row, value_row)

                if pair_item is not None:
                    pair_item.name = normalize_item_name_order(pair_item.name)
                    items.append(pair_item)
                    index = lookahead_index + 1
                    item_added = True
                    break

            if item_added:
                continue

        index += 1

    return items


def parse_layout_items_from_csv(layout_csv_path: str | Path) -> list[LayoutParsedItem]:
    rows = read_layout_rows(layout_csv_path)
    return parse_layout_items_from_rows(rows)


def parse_layout_receipt_items_from_csv(layout_csv_path: str | Path) -> list[ReceiptItem]:
    return [item.to_receipt_item() for item in parse_layout_items_from_csv(layout_csv_path)]


def parse_layout_items_for_receipt(
    receipt_id: str,
    layout_debug_dir: str | Path | None = None,
) -> list[LayoutParsedItem]:
    base_dir = Path(layout_debug_dir) if layout_debug_dir is not None else LAYOUT_DEBUG_DIR
    layout_csv_path = base_dir / f"{receipt_id}_layout_lines.csv"

    return parse_layout_items_from_csv(layout_csv_path)


def parse_layout_receipt_items_for_receipt(
    receipt_id: str,
    layout_debug_dir: str | Path | None = None,
) -> list[ReceiptItem]:
    return [
        item.to_receipt_item()
        for item in parse_layout_items_for_receipt(
            receipt_id=receipt_id,
            layout_debug_dir=layout_debug_dir,
        )
    ]